#!/bin/bash

cfile=$CFILE

base_name="${cfile%.*}"

gcc -c "$cfile" -o "$base_name.o"

#include <stdio.h>

/**
 * main - Entry point
 *
 * Return: Always 0 (Success)
 */
int main(void)
{
    return (0);
}
